version: '3.8'

services:
  postgresql:
    image: postgres:16-alpine
    container_name: postgresql
    environment:
      POSTGRES_DB: companydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P4ssw0rd@2025
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./initdb-postgres.sql:/docker-entrypoint-initdb.d/initdb-postgres.sql
    networks:
      - app-network

  springboot-app:
    image: kosdev92/company:latest
    container_name: springboot-app
    depends_on:
      - postgresql
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/companydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: P4ssw0rd@2025
    ports:
      - "8081:8080"
    networks:
      - app-network

volumes:
  postgresql_data:

networks:
  app-network:
    driver: bridge
