version: "3.8"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: "Express"
      MSSQL_SA_PASSWORD: "p4ssw0rd"
    ports:
      - "1434:1433"
    volumes:
      - db_data:/var/opt/mssql

  app:
    image: kosdev92/company:latest
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data: