name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "World"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean install

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kosdev92/company:latest

    - name: Push the Docker image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push kosdev92/company:latest

    - name: Copy docker-compose-postgres.yml to remote server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: docker-compose-postgres.yml
        target: /home/${{ secrets.SSH_USERNAME }}/company/

    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker rmi kosdev92/company:latest || true
          docker pull kosdev92/company:latest
          cd /home/${{ secrets.SSH_USERNAME }}/company/
          docker compose -f docker-compose-postgres.yml down || true
          docker compose -f docker-compose-postgres.yml up -d
